### ISSUE TITLE
Graphic glitch with default settings "Framebuffer Allocation 3D"

### ISSUE THREAD

**Issue by davcri** [crystal-bit/angry-aliens#2]
With the settings `rendering/quality/intended_usage/framebuffer_allocation` set to `3D` (default value) I have some graphic glitch on the sprites used for the background.
Setting `framebuffer_allocation` to 2D seems to solve the problem (however I still have to commit this change to the repo).

- [Video](https://youtu.be/qjhtqlRF2PM)

![untitled-f000044](https://user-images.githubusercontent.com/6860637/74237328-9764d680-4cd3-11ea-97bb-850253361889.png)

It would be interesting to know if this happens on other devices as well.

Image used for background: [blue_desert.png](https://github.com/crystal-bit/angry-aliens/blob/master/Assets/graphics/kenney_physicsAssets_v2/PNG/Backgrounds/blue_desert.png), 1024x1024px 

```
System:    Kernel: 5.5.2-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.17.5 Distro: Manjaro Linux 
Machine:   Type: Laptop System: Dell product: XPS 15 7590 v: N/A serial: <root required> 
           Mobo: Dell model: 0VYV0G v: A00 serial: <root required> UEFI: Dell v: 1.2.3 date: 07/23/2019 
CPU:       Topology: 6-Core model: Intel Core i7-9750H bits: 64 type: MT MCP L2 cache: 12.0 MiB 
           Speed: 4096 MHz min/max: 800/4500 MHz Core speeds (MHz): 1: 4068 2: 4099 3: 4091 4: 4095 5: 4093 6: 4099 7: 4101 
           8: 4098 9: 4086 10: 4100 11: 4097 12: 4091 
Graphics:  Device-1: Intel UHD Graphics 630 driver: i915 v: kernel 
           Device-2: NVIDIA driver: N/A 
           Display: x11 server: X.Org 1.20.7 driver: intel unloaded: modesetting resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel UHD Graphics 630 (Coffeelake 3x8 GT2) v: 4.6 Mesa 19.3.3 
```

**Comment by dankan1890** [comment]
I don't experience the issue
![no_bug](https://user-images.githubusercontent.com/7107228/74244281-76a37d80-4ce1-11ea-96f9-58c7cf92c31e.gif)

My specs
```
Nome SO		Microsoft Windows 10 Pro
Versione	10.0.19041 build 19041
Tipo sistema	PC basato su x64
Processore	Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz, 3001 Mhz, 4 core
Memoria fisica 	16,0 GB
Nome scheda	Radeon RX 560 Series
RAM scheda	(1.048.576) Byte
Versione driver	26.20.15001.5006
Risoluzione	1600 x 900 x 60 hertz
```

**Comment by davcri** [comment]
Thanks @dankan1890 for reporting. Glad to hear that works fine for you!

I suspect that this problem is specific to my setup.
