### ISSUE TITLE
Random error on startup in Develop branch

### ISSUE THREAD

**Issue by masmartyg** [crystal-bit/angry-aliens#20]
Sometimes, with low probability, this error is generated when starting from editor:
```
Running: D:\Work\Virtual Reality\Godot\Godot_v3.2.2-stable_win64\Godot_v3.2.2-stable_win64.exe --path D:/GoogleDrive/_GODOT/Projects/3.2/angry-aliens-develop --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 3224 --position 485,270
Godot Engine v3.2.2.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: AMD Radeon HD 5700 Series
OpenGL ES 2.0 Batching: ON

ERROR: Node not found: Label.
   At: scene/main/node.cpp:1381
ERROR: Node not found: Label.
   At: scene/main/node.cpp:1381
SCRIPT ERROR: _set_btn_text: Invalid set index 'text' (on base: 'null instance') with value of type 'String'.
          At: res://Objects/GUI/Button1/Button.gd:33
```
Probably due to not fast enough initialization. Sorry, I don't have enough knowledge of Godot to investigate ...

**Comment by davcri** [comment]
Hi @masmartyg thanks for trying the game and reporting the issue! I'll take a look at it in the next days.

What platform were you using when it happened?

**Comment by masmartyg** [comment]
Sorry for the lack of details.

Win10 Pro 1909, Intel i7 920 @ 2.67GHz, AMD Radeon HD 5700.

It happened twice out of ~ten starts. Then I tried another fifteen times just to start and stop but it didn't happen anymore.
I had a similar problem on a project at work (the first one where I use Godot!) but I couldn't figure it out and I finally put a check !=null where the error was, so at least the program doesn't stop.

**Comment by masmartyg** [comment]
I was taking a look at the score scene to understand how it works and out of curiosity I did other tests.
The error no longer appeared to me but on the other hand, by starting the project with F5, the project manager was executed !!!
I think you can close this issue because the problem certainly does not depend on the project.
![Cattura2](https://user-images.githubusercontent.com/41666170/92108409-9c13e800-ede7-11ea-938e-633ee16f0145.PNG)

**Comment by davcri** [comment]
Wow this is funny, I never saw something similar!  
However if you want you can open a pull request that adds the if statement to `res://Objects/GUI/Button1/Button.gd:33`. Otherwise I'll do it during the weekend when I have some free time.

**Comment by davcri** [comment]
I was still getting the error sometimes, so I changed (https://github.com/crystal-bit/angry-aliens/commit/304116b633c2578e3878ab235ed1633602a10f7d) the code in order to use `get_node_or_null`.  
It seems that now the error never fires.

https://github.com/crystal-bit/angry-aliens/blob/304116b633c2578e3878ab235ed1633602a10f7d/Objects/GUI/Button1/Button.gd#L31-L37
